export const GET_CURRENT_CITY_WEATHER_STARTED = 'GET_CURRENT_CITY_WEATHER_STARTED' as const;
export const GET_CURRENT_CITY_WEATHER_SUCCESS = 'GET_CURRENT_CITY_WEATHER_SUCCESS' as const;
export const GET_CURRENT_CITY_WEATHER_FAILURE = 'GET_CURRENT_CITY_WEATHER_FAILURE' as const;

export const REMOVE_CURRENT_CITY_WEATHER = 'REMOVE_CURRENT_CITY_WEATHER' as const;
